#!/bin/bash

#-----------------------------------------------------
# Static Analyze & Build IPA & Uploda 2 fir.im
# Dependency commands: xcodebuild, oclint, xcpretty, fir-cli.
# 
# -s scheme (required)
# -p export plist (required)
# -c configuration, default is release 
# -l oclint static analyze
# -w compile workspace
# -u upload 2 fir, default is no (need fir-cli)
# -t custom fir usertoken
# -n clean before build
#
# Author: Hanran Liu
#-----------------------------------------------------

fir_token="9ad4459a63767d188fe29fe00e880893"
build_config=Release

param_pattern=":s:c:p:t:luwn"
while getopts $param_pattern optname; do
		case "$optname" in
		  "l")
			use_oclint=Y
			;;
		  "n")
			should_clean=Y
			;;
		  "s")
			build_scheme=$OPTARG
			;;
		  "c")
			build_config=$OPTARG
			;;
		  "p")
			export_plist=$OPTARG
			;;
		  "w")
			workspace_name='*.xcworkspace'
			ls $(pwd)/$workspace_name &>/dev/null
			rtnValue=$?
			if [ $rtnValue = 0 ]; then
				build_workspace=$(echo $(basename $(pwd)/$workspace_name))
			else
				echo  "Error!Current path is not a xcode workspace.Please check, or do not use -w option."
				exit 2
			fi
			;;
		  "u")
			upload_fir=Y
			;;
		  "t")
			fir_token=$OPTARG
			;;

		  "?")
	        echo "Error! Unknown option $OPTARG"
			exit 2
	        ;;
	      ":")
	        echo "Error! No argument value for option $OPTARG"
			exit 2
	        ;;
	      *)
	      # Should not occur
	        echo "Error! Unknown error while processing options"
			exit 2
	        ;;
	esac
done

echo "Arguments:\n{scheme: ${build_scheme}, config: ${build_config}, token: ${fir_token}, plist: ${export_plist}}"

rm -rf Product

if [ "$should_clean" = "Y" ]; then
	echo -e "\033[32m ====================================== CLEAN ====================================== \033[0m" 
	xcodebuild clean
fi

if [ "$use_oclint" = "Y" ]; then
	echo -e "\033[32m ====================================== STATIC ANALYZE REPORT ====================================== \033[0m"

	xcodebuild | xcpretty -r json-compilation-database

	cp build/reports/compilation_db.json compile_commands.json

	oclint-json-compilation-database -v \
	-e Pods \
	oclint_args -- -report-type html -o report.html \
	-disable-rule ObjCAssignIvarOutsideAccessors \
	-rc=MINIMUM_CASES_IN_SWITCH=3 \
	-rc=LONG_VARIABLE_NAME=20 \
	-disable-rule ShortVariableName \
	-rc=CYCLOMATIC_COMPLEXITY=10 \
	-rc=LONG_CLASS=1000 \
	-rc=LONG_LINE=250 \
	-rc=LONG_METHOD=80 \
	-rc=NCSS_METHOD=40 \
	-rc=NESTED_BLOCK_DEPTH=5 \
	-rc=TOO_MANY_PARAMETERS=6

	open report.html

	rm -rf build
	rm -rf compile_commands.json
fi

echo -e "\033[32m ====================================== BUILD IPA ====================================== \033[0m" 

mkdir Product
archive_path=Product/${build_scheme}.xcarchive

build_cmd='xcodebuild -archivePath '${archive_path}

if [ "$build_workspace" != "" ]; then
	if [ "$build_scheme" = "" ]; then
		echo "Error! Must provide a scheme by -s option together when using -w option to compile a workspace."
		exit 2
	fi
	#archive workspace
	build_cmd=${build_cmd}' -workspace '${build_workspace}' -sdk iphoneos -scheme '${build_scheme}' -configuration '${build_config}
	else
	#archive project
	build_cmd=${build_cmd}' -sdk iphoneos -configuration '${build_config}
fi

build_cmd=${build_cmd}' archive'
echo "archive command: ${build_cmd}"

#execute
$build_cmd || exit

cd Product
archive_path=./${build_scheme}.xcarchive

#version
bundleShortVersion=$(/usr/libexec/PlistBuddy -c "print :ApplicationProperties:CFBundleShortVersionString" ${archive_path}/Info.plist)
export_path=./${build_scheme}_${bundleShortVersion}.ipa
export_plist=../${export_plist}

xcodebuild -exportArchive -exportOptionsPlist ${export_plist} -archivePath ${archive_path} -exportPath ${export_path} || exit
open .

if [ "$upload_fir" = "Y" ]; then
	echo -e "\033[32m ====================================== FIR LOGIN & UPLOAD ====================================== \033[0m" 

	fir login ${fir_token}
	fir publish *.ipa/*.ipa
fi

